// <auto-generated />
using System;
using AppCrudCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppCrudCore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCrudCore.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Activo = true,
                            Nombre = "Literatura"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Activo = true,
                            Nombre = "Ciencia"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Activo = true,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Activo = true,
                            Nombre = "Historia"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Activo = true,
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            IdCategoria = 6,
                            Activo = true,
                            Nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            IdCategoria = 7,
                            Activo = true,
                            Nombre = "Educación"
                        },
                        new
                        {
                            IdCategoria = 8,
                            Activo = true,
                            Nombre = "Infantil"
                        });
                });

            modelBuilder.Entity("AppCrudCore.Models.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("PrecioPrestamo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StockPrestamo")
                        .HasColumnType("int");

                    b.Property<int>("StockTotal")
                        .HasColumnType("int");

                    b.Property<int>("StockVenta")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdLibro");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("Titulo");

                    b.ToTable("Libro", t =>
                        {
                            t.HasCheckConstraint("CK_Libro_Stock_NoNegativo", "StockTotal >= 0 AND StockPrestamo >= 0 AND StockVenta >= 0");

                            t.HasCheckConstraint("CK_Libro_Stock_Total", "StockPrestamo + StockVenta <= StockTotal");
                        });
                });

            modelBuilder.Entity("AppCrudCore.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Activo = true,
                            Descripcion = "Control completo del sistema",
                            Nombre = "Admin"
                        },
                        new
                        {
                            IdRol = 2,
                            Activo = true,
                            Descripcion = "Gestión de libros y clientes",
                            Nombre = "Empleado"
                        },
                        new
                        {
                            IdRol = 3,
                            Activo = true,
                            Descripcion = "Rol lógico para filtro y sin acceso por el momento",
                            Nombre = "Cliente"
                        });
                });

            modelBuilder.Entity("AppCrudCore.Models.TransaccionBiblioteca", b =>
                {
                    b.Property<int>("IdTransaccionBiblioteca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccionBiblioteca"));

                    b.Property<int>("ClienteUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<string>("ReferenciaPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoPago")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdTransaccionBiblioteca");

                    b.HasIndex("ClienteUsuarioId");

                    b.HasIndex("EmpleadoUsuarioId");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("NumeroTransaccion")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TransaccionBiblioteca");
                });

            modelBuilder.Entity("AppCrudCore.Models.TransaccionDetalle", b =>
                {
                    b.Property<int>("IdTransaccionDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccionDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransaccionBibliotecaId")
                        .HasColumnType("int");

                    b.HasKey("IdTransaccionDetalle");

                    b.HasIndex("LibroId");

                    b.HasIndex("TransaccionBibliotecaId");

                    b.ToTable("TransaccionDetalle");
                });

            modelBuilder.Entity("AppCrudCore.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequiereCambioPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("AppCrudCore.Models.Libro", b =>
                {
                    b.HasOne("AppCrudCore.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AppCrudCore.Models.TransaccionBiblioteca", b =>
                {
                    b.HasOne("AppCrudCore.Models.Usuario", "ClienteUsuario")
                        .WithMany()
                        .HasForeignKey("ClienteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppCrudCore.Models.Usuario", "EmpleadoUsuario")
                        .WithMany()
                        .HasForeignKey("EmpleadoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppCrudCore.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteUsuario");

                    b.Navigation("EmpleadoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppCrudCore.Models.TransaccionDetalle", b =>
                {
                    b.HasOne("AppCrudCore.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppCrudCore.Models.TransaccionBiblioteca", "TransaccionBiblioteca")
                        .WithMany("Detalles")
                        .HasForeignKey("TransaccionBibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("TransaccionBiblioteca");
                });

            modelBuilder.Entity("AppCrudCore.Models.Usuario", b =>
                {
                    b.HasOne("AppCrudCore.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AppCrudCore.Models.TransaccionBiblioteca", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
